# Site settings
title: Julian Tith
email: julian.tith@gmail.com
description: "Full-Stack Web Developer in Training"
keywords: "julian,tith,rawr,chat,avongenesis"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://juliantith.com" # the base hostname & protocol for your site
twitter_username: avongenesis
github_username: avongenesis

# Build settings
markdown: kramdown
author:
    name: Julian Tith
    twitter: avongenesis
    url: http://juliantith.com
    header_bg: /images/profile-header.png
    avatar: /images/avatar.jpg
    email: julian.tith@gmail.com
facebook:
    image: /images/delightfuldev-facebook-cover.png
